import type { GPIngredientDataTypes } from "./types";

// sample data, will only display departments user needs ingredients from
// add/remove departments from list dependent on ingredients user needs
const departments: string[] = [
  "Pasta and Rice",
  "Meat",
  "Sweet Snacks",
  "Frozen",
  "Produce",
  "Milk, Eggs, Other Dairy",
];

const ingredients: GPIngredientDataTypes[] = [
  {
    id: 18,
    department: "Milk, Eggs, Other Dairy",
    image: "",
    ingredientName: "milk",
    quantity: "5",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 17,
    department: "Milk, Eggs, Other Dairy",
    image: "",
    ingredientName: "eggs",
    quantity: "7",
    unit: "units",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 16,
    department: "Milk, Eggs, Other Dairy",
    image: "",
    ingredientName: "yogurt",
    quantity: "3",
    unit: "container/bag",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 15,
    department: "Meat",
    image: "",
    ingredientName: "chicken",
    quantity: "4",
    unit: "units",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 14,
    department: "Condiments",
    image: "",
    ingredientName: "soy sauce",
    quantity: "1",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 13,
    department: "Produce",
    image: "",
    ingredientName: "bananas",
    quantity: "3",
    unit: "units",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 12,
    department: "Bakery/Bread",
    image: "",
    ingredientName: "bread",
    quantity: "12",
    unit: "slices",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 11,
    department: "Milk, Eggs, Other Dairy",
    image: "",
    ingredientName: "cottage cheese",
    quantity: "1",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 1,
    department: "Canned and Jarred",
    image: "",
    ingredientName: "beans",
    quantity: "2",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 2,
    department: "Cheese",
    image: "",
    ingredientName: "cheese",
    quantity: "12",
    unit: "slice",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    id: 3,
    department: "Cereal",
    image: "",
    ingredientName: "cereal",
    quantity: "3",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
];

const groceryList: GPIngredientDataTypes[] = [
  {
    id: 4,
    department: "Pasta and Rice",
    image: "",
    ingredientName: "pasta",
    quantity: "5",
    unit: "cups",
    estimatedCost: 4.0,
  },
  {
    id: 5,
    department: "Meat",
    image: "",
    ingredientName: "ground beef",
    quantity: "1",
    unit: "lb",
    estimatedCost: 4.0,
  },
  {
    id: 6,
    department: "Sweet Snacks",
    image: "",
    ingredientName: "chocolate",
    quantity: "1",
    unit: "bag",
    estimatedCost: 4.0,
  },
  {
    id: 7,
    department: "Frozen",
    image: "",
    ingredientName: "ice cream",
    quantity: "1",
    unit: "tub",
    estimatedCost: 4.0,
  },
  {
    id: 8,
    department: "Produce",
    image: "",
    ingredientName: "spinach",
    quantity: "5",
    unit: "oz",
    estimatedCost: 4.0,
  },
  {
    id: 9,
    department: "Milk, Eggs, Other Dairy",
    image: "",
    ingredientName: "milk",
    quantity: "5",
    unit: "cups",
    estimatedCost: 4.0,
  },
  {
    id: 10,
    department: "Produce",
    image: "",
    ingredientName: "bananas",
    quantity: "3",
    unit: "units",
    estimatedCost: 4.0,
  },
];

export { ingredients, groceryList, departments };
