import type { GPIngredientDataTypes } from "./types";

// sample data, will only display departments user needs ingredients from
// add/remove departments from list dependent on ingredients user needs
const departments: string[] = [
  "Pasta and Rice",
  "Meat",
  "Sweet Snacks",
  "Frozen",
  "Produce",
  "Milk, Eggs, Other Dairy",
];

const ingredients: GPIngredientDataTypes[] = [
  {
    department: "Milk, Eggs, Other Dairy",
    image: "",
    name: "milk",
    quantity: "5",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Milk, Eggs, Other Dairy",
    image: "",
    name: "eggs",
    quantity: "7",
    unit: "units",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Milk, Eggs, Other Dairy",
    image: "",
    name: "yogurt",
    quantity: "3",
    unit: "container/bag",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Meat",
    image: "",
    name: "chicken",
    quantity: "4",
    unit: "units",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Condiments",
    image: "",
    name: "soy sauce",
    quantity: "1",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Produce",
    image: "",
    name: "bananas",
    quantity: "3",
    unit: "units",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Bakery/Bread",
    image: "",
    name: "bread",
    quantity: "12",
    unit: "slices",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Milk, Eggs, Other Dairy",
    image: "",
    name: "cottage cheese",
    quantity: "1",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Canned and Jarred",
    image: "",
    name: "beans",
    quantity: "2",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Cheese",
    image: "",
    name: "cheese",
    quantity: "12",
    unit: "slice",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
  {
    department: "Cereal",
    image: "",
    name: "cereal",
    quantity: "3",
    unit: "cups",
    estimatedCost: 4.0,
    expirationDate: "2025-07-24",
  },
];

const groceryList: GPIngredientDataTypes[] = [
  {
    department: "Pasta and Rice",
    image: "",
    name: "pasta",
    quantity: "5",
    unit: "cups",
    estimatedCost: 4.0,
  },
  {
    department: "Meat",
    image: "",
    name: "ground beef",
    quantity: "1",
    unit: "lb",
    estimatedCost: 4.0,
  },
  {
    department: "Sweet Snacks",
    image: "",
    name: "chocolate",
    quantity: "1",
    unit: "bag",
    estimatedCost: 4.0,
  },
  {
    department: "Frozen",
    image: "",
    name: "ice cream",
    quantity: "1",
    unit: "tub",
    estimatedCost: 4.0,
  },
  {
    department: "Produce",
    image: "",
    name: "spinach",
    quantity: "5",
    unit: "oz",
    estimatedCost: 4.0,
  },
  {
    department: "Milk, Eggs, Other Dairy",
    image: "",
    name: "milk",
    quantity: "5",
    unit: "cups",
    estimatedCost: 4.0,
  },
  {
    department: "Produce",
    image: "",
    name: "bananas",
    quantity: "3",
    unit: "units",
    estimatedCost: 4.0,
  },
];

export { ingredients, groceryList, departments };
